### ISSUE TITLE
initial to-do list

### ISSUE THREAD

**Issue by jessecarterMOOSE** [jessecarterMOOSE/proton_activation#1]
- [ ] Take weight percents of alloying elements and density, return stable isotopes and their atom densities
- [ ] Take those isotopes and an incident proton energy and determine if each isotope at that energy will have a reaction. Either return a bunch of booleans or list of reactions, or product isotopes.
- [ ] Helper script that takes parent nuclide and reaction product and gives the daughter nuclide.
- [ ] Starting with all first-generation daughters, get a list of all products to track.
- [ ] For any given nuclide, need generation rate, either directly from beam as a daughter product, and loss rate from decay constant.
   - [ ] Find if a nuclide can come from multiple sources.
   - [ ] Find if a nuclide has multiple branches.
- [ ] Each nuclide is an ODE in the system, so need to forward the system with beam either on or off.
